data:
  train: 'data/final_dataset_train.tsv'
  testA: 'data/final_dataset_testA.tsv'

feature:
  selected: 'ngram'
  hyperameters:
    ngram:
      kfold: 6

result_dir: 'result'
  
train:
  selected: 'train_test' # chosen from ['train_kfold', 'train_val', 'train_test']
  hyperameters:
    train_kfold: 
      kfold: 10
    train_val:
      split: 0.2
      

model:
  selected: 'lightgbm'
  hyperameters:
    lightgbm:
      built_in:
        objective: 'regression'
        learning_rate: 0.05
        max_depth: 6 
        num_leaves: 32
        bagging_fraction: 0.7
        feature_fraction: 0.7
        num_threads: 64
        verbose: -1
      custom:
        num_boost_round: 2048




      